# Generated by Django 5.1.1 on 2024-10-17 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APaterno', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('AMaterno', models.CharField(max_length=50, verbose_name='Apellido materno')),
                ('Nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Fecha_nacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('Fecha_ingreso', models.DateField(verbose_name='Fecha Ingreso')),
            ],
        ),
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=400, verbose_name='Comenario')),
                ('Alumno_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsecundaria.alumnot')),
            ],
        ),
    ]
