# Generated by Django 5.1.1 on 2024-10-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsecundaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnot',
            name='Nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre(s)'),
        ),
    ]
