# Generated by Django 5.1.1 on 2024-10-17 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsecundaria', '0002_alter_alumnot_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnot',
            options={'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='frase',
            options={'verbose_name': 'Frase', 'verbose_name_plural': 'frases'},
        ),
        migrations.AlterModelTable(
            name='alumnot',
            table='Alumnos',
        ),
    ]
