# Generated by Django 5.1.2 on 2024-10-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsecundaria', '0003_alter_alumnot_options_alter_frase_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnot',
            options={},
        ),
        migrations.AlterModelOptions(
            name='frase',
            options={},
        ),
        migrations.AlterField(
            model_name='alumnot',
            name='AMaterno',
            field=models.CharField(max_length=50, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='alumnot',
            name='Nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='frase',
            name='comentario',
            field=models.TextField(max_length=400, verbose_name='Comentario'),
        ),
        migrations.AlterModelTable(
            name='alumnot',
            table=None,
        ),
    ]
