# Generated by Django 5.1.2 on 2024-10-21 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsecundaria', '0004_alter_alumnot_options_alter_frase_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnot',
            options={'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='frase',
            options={'verbose_name': 'Frase', 'verbose_name_plural': 'frase'},
        ),
        migrations.AlterModelTable(
            name='alumnot',
            table='Alumnos',
        ),
    ]
